version: "3"

services:
  evidence-database:
    image: citusdata/citus:9.4-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password1234
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "55015:5432"
    volumes: 
      - ./psql-setup/:/docker-entrypoint-initdb.d/
    networks:
      evidence-backend-network:
        ipv4_address: 172.20.253.5
  
  evidence-pgadmin4:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: test@mail.com
      PGADMIN_DEFAULT_PASSWORD: password1234
    ports:
      - "55016:80"
    networks:
      evidence-backend-network:
        ipv4_address: 172.20.253.6
