# THIS IS JUST AN EXAMPLE! PLEASE ADJUST IT TO YOUR NEEDS!
version: '3'

services:
  # see https://github.com/citusdata/docker/blob/master/docker-compose.yml
  master:
    container_name: "evidence-database_master"
    image: 'citusdata/citus:10.0.3'
    labels: ['com.citusdata.role=Master']
    environment: &AUTH
      POSTGRES_USER: "${POSTGRES_USER:-postgres}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      PGUSER: "${POSTGRES_USER:-postgres}"
      PGPASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_HOST_AUTH_METHOD: "${POSTGRES_HOST_AUTH_METHOD:-trust}"
    ports:
      - "${DATABASE_HOST_PORT:-5432}:5432"   # 55015
    volumes: 
      - ${POSTGRES_DATA}:/var/lib/postgresql/data   # Persistent on SSD/HDD
      - ./psql-setup/:/docker-entrypoint-initdb.d/   # installation scripts
    networks:
      evidence-backend-network:
        ipv4_address: 172.20.253.5
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
        #window: 300s

  worker:
    image: 'citusdata/citus:10.0.3'
    labels: ['com.citusdata.role=Worker']
    depends_on: [ manager ]
    environment: *AUTH
    command: "/wait-for-manager.sh"
    volumes: 
      - healthcheck-volume:/healthcheck
    networks: [ evidence-backend-network ]  # dynamic IPs!
  
  manager:
    container_name: "evidence-database_manager"
    image: 'citusdata/membership-manager:0.3.0'
    volumes: 
      - "${DATABASE_DOCKER_SOCK:-/var/run/docker.sock}:/var/run/docker.sock"
      - healthcheck-volume:/healthcheck
    depends_on: [ master ]
    environment: *AUTH
    networks:
      evidence-backend-network:
        ipv4_address: 172.20.253.4
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
        #window: 300s

  # see https://www.pgadmin.org/docs/pgadmin4/development/container_deployment.html
  evidence-pgadmin4:
    container_name: evidence-pgadmin4
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "${PGADMIN_HOST_PORT}:80"   # 55016
    networks:
      evidence-backend-network:
        ipv4_address: 172.20.253.6
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
        #window: 300s
    depends_on: [ manager ]

volumes:
  healthcheck-volume:

networks:
  evidence-backend-network:
    name: evidence-backend-network
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.253.0/28
          ip_range: 172.20.253.8/29
