version: '3.7'

services:
  # see https://www.pgadmin.org/docs/pgadmin4/development/container_deployment.html
  evidence-pgadmin4:
    container_name: evidence-pgadmin4
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - ${PGADMIN_HOSTPORT}:80   # 55016
    networks:
      evidence-network:
        ipv4_address: 172.20.253.6
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
        #window: 300s
