-- 
-- Buffer/Cache with raw sentences
-- 
-- Requirements:
-- -------------
--    - it's assumed that the `sentence_id` was generated by the SentenceStore, 
--        and the raw text data is retrieved from the SentenceSTore API
--    - DON'T use this TABLE nor the FUNCTION inside this database!
--    - Call `evidence.get_sentence_text()` only within the Evidence REST API
--        to mimic the SentenceStore API as a temporary solution!
-- 
-- Overview:
-- ---------
--    (A) Required Types => DON'T SPECIFY ANY!
--    (B) Table 
--    (C) Triggers  => DON'T SPECIFY ANY!
--    (D) Other Functions 
-- 


-- -----------------------------------------------------------------------
-- (A) REQUIRED TYPES
-- -----------------------------------------------------------------------

--  n.a.


-- -----------------------------------------------------------------------
-- (B) TABLE 
-- -----------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS 
evidence.sentences_cache (
    sentence_id     uuid NOT NULL
  , sentence_text   text NOT NULL
  , PRIMARY KEY(sentence_id)
);



-- -----------------------------------------------------------------------
-- (C) TRIGGERS 
-- -----------------------------------------------------------------------

-- n.a.


-- -----------------------------------------------------------------------
-- (D) FUNCTIONS 
-- -----------------------------------------------------------------------
CREATE OR REPLACE FUNCTION evidence.get_sentence_text(sent_id uuid)
  RETURNS text AS
$$
BEGIN
  RETURN (SELECT sentence_text FROM evidence.sentences_cache WHERE sentence_id=sent_id);
END;
$$ 
LANGUAGE plpgsql
;

